# Generated by Django 4.2.2 on 2023-06-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='tittle',
        ),
    ]
