# Generated by Django 4.2.2 on 2023-06-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsApp', '0002_rename_title_job_tittle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
    ]
