# Generated by Django 4.2.2 on 2023-06-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsApp', '0003_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-published_at']},
        ),
    ]
